version: "3.8"

services:
  web:
    container_name: django_cont
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - web_app_static_volume:/home/app/static/
    ports:
      - "80:80"

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - web_app_static_volume:/home/app/static/
    depends_on:
      - web

volumes:
  web_app_static_volume:
